CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    facility_type TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT locations_name_address_unique UNIQUE (name, address)
);

CREATE TABLE IF NOT EXISTS routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS route_stops (
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES locations(id),
    stop_order INTEGER NOT NULL CHECK (stop_order > 0),
    PRIMARY KEY (route_id, location_id),
    CONSTRAINT route_stops_order_unique UNIQUE (route_id, stop_order)
);

CREATE INDEX IF NOT EXISTS route_stops_location_idx ON route_stops(location_id);

INSERT INTO locations (name, address, zip_code, facility_type, latitude, longitude)
VALUES
    ('Central Distribution Center', '1201 2nd Ave, Seattle, WA', '98101', 'Distribution center', 47.6082, -122.3371),
    ('Harbor Supply Depot', '2201 Alaskan Way, Seattle, WA', '98121', 'Warehouse', 47.6117, -122.3486),
    ('Downtown Medical Clinic', '901 Boren Ave, Seattle, WA', '98104', 'Medical clinic', 47.6089, -122.3295),
    ('Northside Operations Facility', '4500 Stone Way N, Seattle, WA', '98103', 'Operations facility', 47.6612, -122.3421)
ON CONFLICT (name, address) DO NOTHING;